/*
 * Progression - jQuery plugin for Progress Bar 1.3
 *
 *	http://www.anthor.net/fr/jquery-progression.html
 *
 * Copyright (c) 2008 FOURNET Loïc
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 *
 */

eval(function(p,a,c,k,e,r){e=function(c){return(c<62?'':e(parseInt(c/62)))+((c=c%62)>35?String.fromCharCode(c+29):c.toString(36))};if('0'.replace(0,e)==0){while(c--)r[e(c)]=k[c];k=[function(e){return r[e]||e}];e=function(){return'([2-9n-zA-Z]|1\\w)'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('(5(c){c.s.C=5(e){7 f=c.R({8:50,n:o,S:\'#T\',U:\'#V\',W:\'#FF0000\',X:\'#T\',Y:\'#V\',Z:true,10:3000,11:\'linear\',D:12,r:12},c.s.C.13,e);3(e)7 g=e.8;E 2.14(5(){$2=c(2);$4=$2.F(".15");7 a=c.16?c.R({},f,$2.16()):f;3($4.length!=1)l($2,a);t{3(g)a.8=g;a.n=u($2.9(\'v\'))}3(a.8>a.n){m(\'La 17 demandee doit etre inférieur ou egale a la 17 maximale.\')E G}7 b=q.w(u($2.9(\'x\'))/a.n*o);7 h=q.w(u(a.8)/a.n*o);3(H a.D==\'5\')a.D(a);3(a.Z){7 d=u($2.9(\'x\'));7 j=q.abs(d-a.8);7 k=q.floor(a.10/a.n);$4.I("fx",[]);$4.stop();$4.18({p:h+"%"},{19:q.w(k*(j+1)),I:G,easing:a.11,1a:5(){3(H a.r==\'5\')a.r(a)}});for(i=0;i<=j;i++){$4.18({opacity:1},{19:q.w(k*i),I:G,1a:5(){3(d<=a.8)c(2).y(d++);t c(2).y(d--)}})}}t{$4.6({p:h+\'%\'});$4.y(a.8);3(H a.r==\'5\')a.r(a)}})};5 l(a,b){a.J(\'\');a.6({K:\'left\',z:\'relative\',1b:\'1c\',1d:b.S,borderColor:b.Y,1e:b.U});3(b.1f)a.6(\'p\',b.1f);3(b.L)a.6({M:b.L,lineHeight:b.L});3(b.1g)a.6({1h:\'1i(\'+b.1g+\')\'});$4=c("<A N=\'15\'></A>");c("<A N=\'B\'>&1j;</A>").6({z:\'O\',p:\'o%\',M:\'o%\',K:\'1k\'}).1l(a);c("<1m N=\'B\'>&1j;</1m>").6({z:\'O\',p:a.p(),K:\'1k\'}).1l($4);a.append($4);$4.6({z:\'O\',p:0,M:\'o%\',1b:\'1c\',1d:b.W,1e:b.X});3(b.1n)$4.6({1h:\'1i(\'+b.1n+\')\'});a.9(\'v\',b.n);a.9(\'x\',0)};c.s.y=5(a){E 2.14(5(){$2=c(2).parent();3($2.9(\'v\')!=o)$2.F(".B").J(a+"/"+$2.9(\'v\'));t $2.F(".B").J(a+" %");$2.9(\'x\',a)})};5 m(a){3(P.Q&&P.Q.1o)P.Q.1o(\'1p Progression: \'+a)};c.s.C.13={}})(1p);',[],88,'||this|if|innerdiv|function|css|var|Current|attr||||||||||||||Maximum|100|width|Math|endFct|fn|else|parseInt|pmax|round|pcur|progressionSetTextTo|position|div|text|progression|startFct|return|find|false|typeof|queue|html|textAlign|Height|height|class|absolute|window|console|extend|Background|FFFFFF|TextColor|000000|aBackground|aTextColor|BorderColor|Animate|AnimateTimeOut|Easing|null|defaults|each|progress|metadata|valeur|animate|duration|complete|overflow|hidden|backgroundColor|color|Width|BackgroundImg|backgroundImage|url|nbsp|center|appendTo|span|aBackgroundImg|log|jQuery'.split('|'),0,{}))