<?php

if(isset($root) AND isset($iroot)){
$locations_images=Array(// Posizione  immagini
                          "img_pallino_marrone"     =>$iroot."images/ball_brown.png",
                          "img_pallino_verde"       =>$iroot."images/ball_green.png",
                          "img_pallino_blu"         =>$iroot."images/ball_blue.png",
                          "img_pallino_grigio"      =>$iroot."images/ball_grey.png",
                          "img_pallino_arancio"     =>$iroot."images/ball_violet.gif",
                          "img_pallino_rosso"       =>$iroot."images/ball_red.png",
                          
                          "icn_pallino_marrone"     =>$iroot."images/icons/brown_16.png",
                          "icn_pallino_verde"       =>$iroot."images/icons/green_16.png",
                          "icn_pallino_blu"         =>$iroot."images/icons/blue_16.png",
                          "icn_pallino_grigio"      =>$iroot."images/icons/grey_16.png",
                          "icn_pallino_rosso"       =>$iroot."images/icons/red_16.png",
                          
                          "Map-Marker-Ball-Chartreuse-icon-16"=>$iroot."images/icons/Map-Marker-Ball-Chartreuse-icon-16.png",
                          
 //Vecchio logo           "img_logo"                =>$iroot."images/".read_option_text(0,"IMG_LOGO"),
                          "img_logo"                =>$iroot."images/rg_18.png",
                          "img_logo_retedes"        =>$iroot."images/logo_retedes_v11_200x200.png",
                          "birra_1"                 =>$iroot."images/Boccale.png",
                          "birra_2"                 =>$iroot."images/Boccale_2.png",
                          "birra_3"                 =>$iroot."images/Boccale_3.png",
                          "img_forbici"             =>$iroot."images/forbici.png",
                          "ajax_loader"             =>$iroot."images/ajax-loader.gif",
                          "img_pacco"               =>$iroot."images/pacco.png",
                          "img_home_piccola"        =>$iroot."images/hp.gif",
                          "img_logout"              =>$iroot."images/exit.jpg",
                          "img_piemonte_cuore_s"    =>$iroot."images/piemonte_cuore_small_2.png",
  //                      "img_piemonte_cuore_s"    =>$iroot."images/rg_italia_75x75.png",
  //Wurstel               "img_piemonte_cuore_s"    =>"http://2.bp.blogspot.com/_VXFMKDirfQ0/S_7tyRd8K3I/AAAAAAAAAPE/IZozXDwgwqI/s1600/wurstel.jpg",
                          "img_chrome_logo"         =>$iroot."images/chrome-logo-300x291.jpg",
                          "logo_coseinutili"        =>$iroot."images/logo2coseinutili.png",
                          "img_omino"               =>$iroot."images/omino.png",
                          "img_omino_2"             =>$iroot."images/star_blu.png",
                          "img_carrello"            =>$iroot."images/cart.png",
                          "img_gas_home"            =>$iroot."images/GAS.png",
                          "img_icona_grafico"       =>$iroot."images/grafico.png",
                          "img_icona_scheda"        =>$iroot."images/ico_scheda.png",
                          "img_icona_numeri"        =>$iroot."images/numbers.png",
                          "img_qrcode_art_ord_si"   =>$iroot."ordini_chiusi/articoli_ordinati_scatole_intere/oc_art_ord_report.php",
                          "img_qrcode_av_amm"       =>$iroot."ordini_chiusi/articoli_ordinati/oc_art_ord_av_amm_report.php",
                          "img_qrcode_oc_art_ord"   =>$iroot."ordini_chiusi/articoli_ordinati/oc_art_ord_report.php",
                          "img_ss1"                 =>$iroot."images/ss/ss1.JPG",
                          "img_ss2"                 =>$iroot."images/ss/ss2.JPG",
                          "img_ss3"                 =>$iroot."images/ss/ss3.JPG",
                          "img_ss4"                 =>$iroot."images/ss/ss4.JPG",
                          "img_ss5"                 =>$iroot."images/ss/ss5.JPG",
                          "img_ss6"                 =>$iroot."images/ss/ss6.JPG",
                          "img_ss7"                 =>$iroot."images/ss/ss7.JPG",
                          "img_ss8"                 =>$iroot."images/ss/ss8.JPG",     
                          "img_ss9"                 =>$iroot."images/ss/ss9.JPG",
                          "img_ss10"                =>$iroot."images/ss/ss10.JPG",
                          "img_ss11"                =>$iroot."images/ss/ss11.JPG",
                          "img_ss12"                =>$iroot."images/ss/ss12.JPG");
}
